### ISSUE TITLE
Links in ALL new merged local pages are broken

### ISSUE THREAD

**Issue by 5HT** [synrc/n2o.dev#13]
This is ridiculous. In every local page link goes to EN version ? This is a marker that changes was introduced without testing.

**Comment by 5HT** [comment]
This is ridiculous. In every local page link goes to EN version ? This is a marker that changes was introduced without testing.

**Comment by 221V** [comment]
i do not understand what links and where are broken

if you talking about DE lang version pages --
i do not make translations for DE, 
i do not change texts at that pages,
i just make links (and nothing more) for that some translated
and prepared for thanslations pages -- copied to DE folders from EN,
(but not me made that DE folders and pages)

if you want i can remove all DE links
