### ISSUE TITLE
404 for forms.css in all form pages

### ISSUE THREAD

**Issue by andrew-demb** [synrc/n2o.dev#17]
Included CSS file `priv/static/css/forms.css` in form pages cannot be fetched. 
Is this file are excess and import should be dropped?

Example page - https://form.n2o.dev/

**Comment by 5HT** [comment]
Could you point to pages in git repo ?

**Comment by andrew-demb** [comment]
https://github.com/synrc/n2o.dev/blob/f644e0b5e95a798ee9265d443608ddd8c5cc9ca0/deps/form/man/de/index.html

https://github.com/synrc/n2o.dev/blob/348b28fcc27d12370be944a20e202929173faf2c/deps/form/man/ua/index.html

Can't find entry with css for main page - https://form.n2o.dev/. I think it is not affected.

**Comment by 5HT** [comment]
Is there any reason you post links pointing not to master?
I replaced all the occurances of 

`https://form.n2o.dev/priv/static/css/forms.css`

to

`https://form.n2o.dev/priv/css/form.css`

in this repo. Closing.
