### ISSUE TITLE
UA Translations

### ISSUE THREAD

**Issue by 5HT** [synrc/n2o.dev#8]
* MAD
* NITRO
* FORMS
* FS
* SH -> EXE: rename also `sh_ ` prefixes, application, package.

**Comment by 221V** [comment]
"SH -> EXE: rename .." -- means only for UA translated version, or for EN version too?
ok, "application" says -- EN too, because app located there
sh in subdomain "sh.n2o.space" (CNAME file) needs rename too ?

**Comment by 221V** [comment]
sh in subdomain "sh.n2o.space" (CNAME file) needs rename too ?

**Comment by 5HT** [comment]
Just ignore this `SH -> EXE` subtask.

**Comment by 221V** [comment]
subtask in process,
ignore change subdomain, man and code -- will end changing now

**Comment by 5HT** [comment]
Задача начебто виконана проте те що людина не змогла з 10-го разу зробити коміт який автоматично мержиться, означає що працювати з цією людиною на гітхабі ніхто не буде. Нажаль, до побачення.
